# Generated by Django 3.1.1 on 2020-09-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
